In [3]:
import pickle
import numpy as np
import sys
sys.path.append(r"D:\HopeAI\Assignments\MyModules")
from data_analysis_utils import Preprocessing

In [ ]:
filename=r'D:\HopeAI\Assignments\ML and DS Capstone\2. Data Preprocessing\pre_dataset.pkl'
dataset = pickle.load( open(filename,'rb'))

quan, _ = Preprocessing.quanQual(dataset)

dataset

,Stock,Sector,Industry,MarketCap,Cap Category,Annualized_Return,Annualized_Volatility,Sharpe_Ratio,Max_Drawdown,Avg_Volume,Volume_Spike_Pct,Beta_vs_NIFTY,Corr_with_NIFTY
0,360ONE,Financial Services,Asset Management,445803167744,Mid Cap,3.524515,0.589975,5.889254,30.097756,4.899030e+05,11.111111,0.639538,0.260950
1,AARTIIND,Basic Materials,Specialty Chemicals,138456645632,Small Cap,-0.517008,0.585279,-0.968783,63.172265,1.300992e+06,7.317073,1.252114,0.514999
2,ABB,Industrials,Specialty Industrial Machinery,1090798354432,Large Cap,2.615783,0.571198,4.491934,26.442369,3.516467e+05,6.368564,0.862478,0.363485
3,ABCAPITAL,Financial Services,Financial Conglomerates,781306822656,Mid Cap,0.639011,0.573486,1.027072,35.630066,5.000453e+06,9.214092,1.392779,0.584635
4,ABREL,Basic Materials,Paper & Paper Products,178644762624,Small Cap,2.476973,0.697101,3.481524,39.647621,3.216849e+05,10.704607,1.227745,0.423973
...,...,...,...,...,...,...,...,...,...,...,...,...,...
262,WIPRO,Technology,Information Technology Services,2567080247296,Large Cap,-0.058463,0.432499,-0.250782,50.015772,1.370024e+07,5.555556,1.081205,0.601794
263,WOCKPHARMA,Healthcare,Drug Manufacturers - Specialty & Generic,225707163648,Small Cap,4.216138,0.828349,5.029448,63.056593,1.059813e+06,10.027100,0.982579,0.285548
264,YESBANK,Financial Services,Banks - Regional,754220466176,Mid Cap,0.777135,0.707369,1.027943,39.267516,1.655482e+08,10.569106,1.091840,0.371568
265,ZENTEC,Industrials,Aerospace & Defense,125330620416,Small Cap,14.446618,0.809376,17.787296,34.040224,5.798867e+05,10.840108,0.969627,0.288389
266,ZYDUSLIFE,Healthcare,Drug Manufacturers - Specialty & Generic,1001705963520,Large Cap,1.248345,0.436244,2.746960,30.832901,1.421235e+06,7.046070,0.695241,0.383646

## Remove Highly Correlated Features

In [5]:
data_corr=dataset[quan].corr()
data_corr.corr()

,MarketCap,Annualized_Return,Annualized_Volatility,Sharpe_Ratio,Max_Drawdown,Avg_Volume,Volume_Spike_Pct,Beta_vs_NIFTY,Corr_with_NIFTY
MarketCap,1.000000,-0.581676,-0.929966,-0.500636,-0.655922,-0.045733,-0.919886,-0.057982,0.760361
Annualized_Return,-0.581676,1.000000,0.630521,0.993935,-0.078162,-0.332812,0.611032,-0.262085,-0.681947
Annualized_Volatility,-0.929966,0.630521,1.000000,0.544717,0.689798,0.008332,0.944698,0.007720,-0.831191
Sharpe_Ratio,-0.500636,0.993935,0.544717,1.000000,-0.185190,-0.346183,0.531654,-0.278860,-0.620879
Max_Drawdown,-0.655922,-0.078162,0.689798,-0.185190,1.000000,0.174470,0.629957,0.128930,-0.491872
Avg_Volume,-0.045733,-0.332812,0.008332,-0.346183,0.174470,1.000000,0.011487,0.130531,0.050254
Volume_Spike_Pct,-0.919886,0.611032,0.944698,0.531654,0.629957,0.011487,1.000000,-0.182504,-0.901389
Beta_vs_NIFTY,-0.057982,-0.262085,0.007720,-0.278860,0.128930,0.130531,-0.182504,1.000000,0.546607
Corr_with_NIFTY,0.760361,-0.681947,-0.831191,-0.620879,-0.491872,0.050254,-0.901389,0.546607,1.000000

In [6]:

corr_matrix = dataset[quan].corr().abs()  # Absolute correlations
upper_triangle = corr_matrix.where(np.triu(np.ones(corr_matrix.shape), k=1).astype(bool))

# Find columns to drop with correlation > 0.75
to_drop = [column for column in upper_triangle.columns if any(upper_triangle[column] > 0.75)]

print("Features to remove:", to_drop)

Features to remove: ['Sharpe_Ratio']

## Remove the Unnecessary Columns

In [5]:
dataset_reduced = dataset.drop(columns=to_drop)
dataset_reduced.columns

Index(['Stock', 'Sector', 'Industry', 'MarketCap', 'Cap Category',
       'Annualized_Return', 'Annualized_Volatility', 'Max_Drawdown',
       'Avg_Volume', 'Volume_Spike_Pct', 'Beta_vs_NIFTY', 'Corr_with_NIFTY'],
      dtype='object')

In [ ]:
filename="dataset_reduced.pkl"
pickle.dump(dataset_reduced, open(filename,'wb'))

cols_to_drop = ['Stock', 'Sector', 'Industry','Cap Category']
dataset_unscaled = dataset_reduced.drop(cols_to_drop, axis=1)
filename="dataset_unscaled.pkl"
pickle.dump(dataset_unscaled, open(filename,'wb'))
dataset_unscaled

,MarketCap,Annualized_Return,Annualized_Volatility,Max_Drawdown,Avg_Volume,Volume_Spike_Pct,Beta_vs_NIFTY,Corr_with_NIFTY
0,445803167744,3.524515,0.589975,30.097756,4.899030e+05,11.111111,0.639538,0.260950
1,138456645632,-0.517008,0.585279,63.172265,1.300992e+06,7.317073,1.252114,0.514999
2,1090798354432,2.615783,0.571198,26.442369,3.516467e+05,6.368564,0.862478,0.363485
3,781306822656,0.639011,0.573486,35.630066,5.000453e+06,9.214092,1.392779,0.584635
4,178644762624,2.476973,0.697101,39.647621,3.216849e+05,10.704607,1.227745,0.423973
...,...,...,...,...,...,...,...,...
262,2567080247296,-0.058463,0.432499,50.015772,1.370024e+07,5.555556,1.081205,0.601794
263,225707163648,4.216138,0.828349,63.056593,1.059813e+06,10.027100,0.982579,0.285548
264,754220466176,0.777135,0.707369,39.267516,1.655482e+08,10.569106,1.091840,0.371568
265,125330620416,14.446618,0.809376,34.040224,5.798867e+05,10.840108,0.969627,0.288389
266,1001705963520,1.248345,0.436244,30.832901,1.421235e+06,7.046070,0.695241,0.383646