In [5]:
import pandas as pd

data = pd.read_csv('Placement.csv')
print(data['gender'].dtypes)

object

In [11]:
qual = []
quan = []
for columnNames in data.columns:
    # print(columnNames)
    if data[columnNames].dtype == 'object':
        qual.append(columnNames)
    else:
        quan.append(columnNames)
print(qual, quan)

['gender', 'ssc_b', 'hsc_b', 'hsc_s', 'degree_t', 'workex', 'specialisation', 'status'] ['sl_no', 'ssc_p', 'hsc_p', 'degree_p', 'etest_p', 'mba_p', 'salary']

In [13]:
data.describe()

,sl_no,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary
count,215.000000,215.000000,215.000000,215.000000,215.000000,215.000000,148.000000
mean,108.000000,67.303395,66.333163,66.370186,72.100558,62.278186,288655.405405
std,62.209324,10.827205,10.897509,7.358743,13.275956,5.833385,93457.452420
min,1.000000,40.890000,37.000000,50.000000,50.000000,51.210000,200000.000000
25%,54.500000,60.600000,60.900000,61.000000,60.000000,57.945000,240000.000000
50%,108.000000,67.000000,65.000000,66.000000,71.000000,62.000000,265000.000000
75%,161.500000,75.700000,73.000000,72.000000,83.500000,66.255000,300000.000000
max,215.000000,89.400000,97.700000,91.000000,98.000000,77.890000,940000.000000

In [15]:
descriptive = pd.DataFrame(index = ['Mean', 'Median', 'Mode'], columns = quan)
descriptive

       sl_no ssc_p hsc_p degree_p etest_p mba_p salary
Mean     NaN   NaN   NaN      NaN     NaN   NaN    NaN
Median   NaN   NaN   NaN      NaN     NaN   NaN    NaN
Mode     NaN   NaN   NaN      NaN     NaN   NaN    NaN

In [25]:
data['mba_p'].mode()[0]

np.float64(56.7)

In [27]:
for columnName in quan:
    descriptive.loc['Mean', columnName] = data[columnName].mean().round(2)
    descriptive.loc['Median', columnName] = data[columnName].median()
    descriptive.loc['Mode', columnName] = data[columnName].mode()[0]
descriptive

        sl_no ssc_p  hsc_p degree_p etest_p  mba_p     salary
Mean    108.0  67.3  66.33    66.37    72.1  62.28  288655.41
Median  108.0  67.0   65.0     66.0    71.0   62.0   265000.0
Mode        1  62.0   63.0     65.0    60.0   56.7   300000.0