## Import Modules and Dataset

In [1]:
import pandas as pd
import data_analysis_utils as utils
import selectKregression as k_regr

inp_dataset = pd.read_csv('kidney_disease.csv')
inp_dataset = pd.read_csv('kidney_disease.csv').drop(columns='id')

inp_dataset

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,48.0,80.0,1.020,1.0,0.0,NaN,normal,notpresent,notpresent,121.0,...,44,7800,5.2,yes,yes,no,good,no,no,ckd
1,7.0,50.0,1.020,4.0,0.0,NaN,normal,notpresent,notpresent,NaN,...,38,6000,NaN,no,no,no,good,no,no,ckd
2,62.0,80.0,1.010,2.0,3.0,normal,normal,notpresent,notpresent,423.0,...,31,7500,NaN,no,yes,no,poor,no,yes,ckd
3,48.0,70.0,1.005,4.0,0.0,normal,abnormal,present,notpresent,117.0,...,32,6700,3.9,yes,no,no,poor,yes,yes,ckd
4,51.0,80.0,1.010,2.0,0.0,normal,normal,notpresent,notpresent,106.0,...,35,7300,4.6,no,no,no,good,no,no,ckd
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,55.0,80.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,140.0,...,47,6700,4.9,no,no,no,good,no,no,notckd
396,42.0,70.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,75.0,...,54,7800,6.2,no,no,no,good,no,no,notckd
397,12.0,80.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,100.0,...,49,6600,5.4,no,no,no,good,no,no,notckd
398,17.0,60.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,114.0,...,51,7200,5.9,no,no,no,good,no,no,notckd
399,58.0,80.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,131.0,...,53,6800,6.1,no,no,no,good,no,no,notckd

## Analysing Raw data and Preprocess

In [2]:
print('Missing Value Percentages:', inp_dataset.isnull().mean()*100)

quan, qual = utils.Preprocessing.quanQual(inp_dataset)
inp_dataset = utils.Preprocessing.quanVariables(inp_dataset, qual)

Missing Value Percentages: age                2.25
bp                 3.00
sg                11.75
al                11.50
su                12.25
rbc               38.00
pc                16.25
pcc                1.00
ba                 1.00
bgr               11.00
bu                 4.75
sc                 4.25
sod               21.75
pot               22.00
hemo              13.00
pcv               17.50
wc                26.25
rc                32.50
htn                0.50
dm                 0.50
cad                0.50
appet              0.25
pe                 0.25
ane                0.25
classification     0.00
dtype: float64

In [3]:
inp_dataset[['pcv', 'rc', 'wc']]=inp_dataset[['pcv', 'rc', 'wc']].astype(float)
quan, qual = utils.Preprocessing.quanQual(inp_dataset)

In [4]:
inp_dataset = utils.Preprocessing.simple_missing(inp_dataset, quan, qual)
inp_dataset = utils.Preprocessing.model_missing(inp_dataset, quan)

## Input, Target variables split

In [5]:
data = pd.get_dummies(inp_dataset, drop_first=True)
indep_X = data.iloc[:, :-1]
dep_Y = data.iloc[:, -1]

## Feature Selection

In [6]:
fullresult = pd.DataFrame()
for n in range(3,7):
    result = k_regr.run_regressors(indep_X, dep_Y, n)
    fullresult = pd.concat([fullresult, result], ignore_index=True)


fullresult

,K_No,Linear_R2,Ridge_R2,SVMl_R2,SVMnl_R2,KNN_R2,DecisionTree_R2,RandomForest_R2
0,3,0.730731,0.730556,0.717969,0.934603,0.936429,0.894167,0.943163
1,4,0.714546,0.714658,0.690447,0.909986,0.897900,0.957191,0.922628
2,5,0.725350,0.725430,0.693244,0.910065,0.890195,0.890195,0.893959
3,6,0.736304,0.736377,0.709517,0.894463,0.872857,0.890195,0.896901

In [7]:
max_Accuracy = fullresult.iloc[:,1:].values.max()

max_pos = fullresult.iloc[:, 1:].stack().idxmax()  # (row_index, column_name)

row_index = max_pos[0]
Model_Name = max_pos[1]

k_No = fullresult.iloc[row_index, 0]

print(f'Max Accuracy is: {max_Accuracy:.4f}% for {Model_Name} Model with K = {k_No} ')

Max Accuracy is: 0.9572% for DecisionTree_R2 Model with K = 4