In [6]:
import pandas as pd
import data_analysis_utils as utils
import pca_regression as pca_regr 
from sklearn.preprocessing import StandardScaler

In [7]:

inp_dataset = pd.read_csv('insurance_pre.csv')

inp_dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [8]:
print('Missing Value Percentages:', inp_dataset.isnull().mean()*100)

Missing Value Percentages: age         0.0
sex         0.0
bmi         0.0
children    0.0
smoker      0.0
charges     0.0
dtype: float64

In [9]:
print('Missing Value Percentages:', inp_dataset.isnull().mean()*100)

quan, qual = utils.Preprocessing.quanQual(inp_dataset)
inp_dataset = utils.Preprocessing.quanVariables(inp_dataset, qual)

Missing Value Percentages: age         0.0
sex         0.0
bmi         0.0
children    0.0
smoker      0.0
charges     0.0
dtype: float64

In [10]:
quan_data = inp_dataset[quan]
quan_scaler = StandardScaler()
quan_scaled = quan_scaler.fit_transform(quan_data)
scaled_data = pd.DataFrame(quan_scaled, columns=quan)
scaled_data[qual] = inp_dataset[qual]

data = pd.get_dummies(scaled_data, drop_first=True)
indep_X = data.iloc[:, :-1]
dep_Y = data.iloc[:, -1]

In [15]:

fullresult = pd.DataFrame()
for n in range(1,5):
    result = pca_regr.pca_regressors(indep_X, dep_Y, n)
    fullresult = pd.concat([fullresult, result], ignore_index=True)


fullresult

,No_Of_Components,Linear,Ridge,SVMl,SVMnl,KNN,DecisionTree,RandomForest
0,1,0.179927,0.179893,-0.071819,0.146961,0.102814,-0.643396,-0.145863
1,2,0.172121,0.172098,-0.071845,0.163851,0.125930,-0.462803,0.119429
2,3,0.180539,0.180528,-0.071527,0.201881,0.164938,-0.119677,0.212434
3,4,0.689494,0.689471,0.687671,0.754741,0.804237,0.729111,0.789609

In [16]:
max_val = fullresult.iloc[:, 1:].values.max()
row, col = fullresult.iloc[:, 1:].stack().idxmax()
no_features = fullresult.iloc[row, 0]
print(f'Max Accuracy is: {max_val:.4f}% for {col} Model  \nWith No of Features = {no_features}')

Max Accuracy is: 0.8042% for KNN Model
With No of Features = 4