In [53]:
import yfinance as yf
import pandas as pd

In [54]:
large_tickers=[
"ABB.NS",
"ADANIENSOL.NS",
"ADANIENT.NS",
"ADANIGREEN.NS",
"ADANIPORTS.NS",
"ADANIPOWER.NS",
"AMBUJACEM.NS",
"APOLLOHOSP.NS",
"ASIANPAINT.NS",
"DMART.NS",
"AXISBANK.NS",
"BAJAJ-AUTO.NS",
"BAJFINANCE.NS",
"BAJAJFINSV.NS",
"BAJAJHLDNG.NS",
"BAJAJHFL.NS",
"BANKBARODA.NS",
"BEL.NS",
"BPCL.NS",
"BHARTIARTL.NS",
"BOSCHLTD.NS",
"BRITANNIA.NS",
"CGPOWER.NS",
"CANBK.NS",
"CHOLAFIN.NS",
"CIPLA.NS",
"COALINDIA.NS",
"DLF.NS",
"DIVISLAB.NS",
"DRREDDY.NS",
"EICHERMOT.NS",
"ETERNAL.NS",
"GAIL.NS",
"GODREJCP.NS",
"GRASIM.NS",
"HCLTECH.NS",
"HDFCBANK.NS",
"HDFCLIFE.NS",
"HAVELLS.NS",
"HINDALCO.NS",
"HAL.NS",
"HINDUNILVR.NS",
"HINDZINC.NS",
"HYUNDAI.NS",
"ICICIBANK.NS",
"ICICIGI.NS",
"ITC.NS",
"INDHOTEL.NS",
"IOC.NS",
"IRFC.NS",
"NAUKRI.NS",
"INFY.NS",
"INDIGO.NS",
"JSWENERGY.NS",
"JSWSTEEL.NS",
"JINDALSTEL.NS",
"JIOFIN.NS",
"KOTAKBANK.NS",
"LTIM.NS",
"LT.NS",
"LICI.NS",
"LODHA.NS",
"M&M.NS",
"MARUTI.NS",
"MAXHEALTH.NS",
"MAZDOCK.NS",
"NTPC.NS",
"NESTLEIND.NS",
"ONGC.NS",
"PIDILITIND.NS",
"PFC.NS",
"POWERGRID.NS",
"PNB.NS",
"RECLTD.NS",
"RELIANCE.NS",
"SBILIFE.NS",
"MOTHERSON.NS",
"SHREECEM.NS",
"SHRIRAMFIN.NS",
"SIEMENS.NS",
"SOLARINDS.NS",
"SBIN.NS",
"SUNPHARMA.NS",
"TVSMOTOR.NS",
"TCS.NS",
"TATACONSUM.NS",
"TATAMOTORS.NS",
"TATAPOWER.NS",
"TATASTEEL.NS",
"TECHM.NS",
"TITAN.NS",
"TORNTPHARM.NS",
"TRENT.NS",
"ULTRACEMCO.NS",
"UNITDSPR.NS",
"VBL.NS",
"VEDL.NS",
"WIPRO.NS",
"ZYDUSLIFE.NS",
]

In [55]:
mid_tickers=[
"360ONE.NS",
"ACC.NS",
"APLAPOLLO.NS",
"AUBANK.NS",
"ATGL.NS",
"ABCAPITAL.NS",
"ALKEM.NS",
"ASHOKLEY.NS",
"ASTRAL.NS",
"AUROPHARMA.NS",
"BSE.NS",
"BANKINDIA.NS",
"BDL.NS",
"BHARATFORG.NS",
"BHEL.NS",
"BHARTIHEXA.NS",
"BIOCON.NS",
"BLUESTARCO.NS",
"COCHINSHIP.NS",
"COFORGE.NS",
"COLPAL.NS",
"CONCOR.NS",
"COROMANDEL.NS",
"CUMMINSIND.NS",
"DABUR.NS",
"DIXON.NS",
"EXIDEIND.NS",
"NYKAA.NS",
"FEDERALBNK.NS",
"FORTIS.NS",
"GMRAIRPORT.NS",
"GLENMARK.NS",
"GODFRYPHLP.NS",
"GODREJPROP.NS",
"HDFCAMC.NS",
"HEROMOTOCO.NS",
"HINDPETRO.NS",
"POWERINDIA.NS",
"HUDCO.NS",
"IDFCFIRSTB.NS",
"IRB.NS",
"INDIANB.NS",
"IRCTC.NS",
"IREDA.NS",
"IGL.NS",
"INDUSTOWER.NS",
"INDUSINDBK.NS",
"JUBLFOOD.NS",
"KEI.NS",
"KPITTECH.NS",
"KALYANKJIL.NS",
"LTF.NS",
"LICHSGFIN.NS",
"LUPIN.NS",
"MRF.NS",
"M&MFIN.NS",
"MANKIND.NS",
"MARICO.NS",
"MFSL.NS",
"MOTILALOFS.NS",
"MPHASIS.NS",
"MUTHOOTFIN.NS",
"NHPC.NS",
"NMDC.NS",
"NTPCGREEN.NS",
"NATIONALUM.NS",
"OBEROIRLTY.NS",
"OIL.NS",
"PAYTM.NS",
"OFSS.NS",
"POLICYBZR.NS",
"PIIND.NS",
"PAGEIND.NS",
"PATANJALI.NS",
"PERSISTENT.NS",
"PHOENIXLTD.NS",
"POLYCAB.NS",
"PREMIERENE.NS",
"PRESTIGE.NS",
"RVNL.NS",
"SBICARD.NS",
"SRF.NS",
"SONACOMS.NS",
"SAIL.NS",
"SUPREMEIND.NS",
"SUZLON.NS",
"SWIGGY.NS",
"TATACOMM.NS",
"TATAELXSI.NS",
"TATATECH.NS",
"TORNTPOWER.NS",
"TIINDIA.NS",
"UPL.NS",
"UNIONBANK.NS",
"VMM.NS",
"IDEA.NS",
"VOLTAS.NS",
"WAAREEENER.NS",
"YESBANK.NS",

]

In [56]:
small_tickers=[
"AADHARHFC.NS",
"AARTIIND.NS",
"ABREL.NS",
"AEGISLOG.NS",
"AFCONS.NS",
"AFFLE.NS",
"ARE&M.NS",
"AMBER.NS",
"ANANDRATHI.NS",
"ANANTRAJ.NS",
"ANGELONE.NS",
"APTUS.NS",
"ASTERDM.NS",
"ATUL.NS",
"BEML.NS",
"BLS.NS",
"BANDHANBNK.NS",
"FIRSTCRY.NS",
"BRIGADE.NS",
"CESC.NS",
"CGCL.NS",
"CASTROLIND.NS",
"CDSL.NS",
"CHAMBLFERT.NS",
"CHOLAHLDNG.NS",
"CAMS.NS",
"CREDITACC.NS",
"CROMPTON.NS",
"CYIENT.NS",
"DATAPATTNS.NS",
"DEEPAKFERT.NS",
"DELHIVERY.NS",
"DEVYANI.NS",
"LALPATHLAB.NS",
"FSL.NS",
"FIVESTAR.NS",
"GRSE.NS",
"GILLETTE.NS",
"GLAND.NS",
"GODIGIT.NS",
"GESHIP.NS",
"HBLENGINE.NS",
"HSCL.NS",
"HINDCOPPER.NS",
"IFCI.NS",
"IIFL.NS",
"IRCON.NS",
"IEX.NS",
"INOXWIND.NS",
"IGIL.NS",
"IKS.NS",
"JBCHEPHARM.NS",
"JBMA.NS",
"JINDALSAW.NS",
"JWL.NS",
"JYOTICNC.NS",
"KAJARIACER.NS",
"KPIL.NS",
"KARURVYSYA.NS",
"KAYNES.NS",
"KEC.NS",
"KFINTECH.NS",
"LAURUSLABS.NS",
"MGL.NS",
"MANAPPURAM.NS",
"MRPL.NS",
"MCX.NS",
"NATCOPHARM.NS",
"NBCC.NS",
"NCC.NS",
"NH.NS",
"NAVINFLUOR.NS",
"NEULANDLAB.NS",
"NEWGEN.NS",
"NUVAMA.NS",
"OLAELEC.NS",
"PCBL.NS",
"PGEL.NS",
"PNBHOUSING.NS",
"PPLPHARMA.NS",
"POONAWALLA.NS",
"RADICO.NS",
"REDINGTON.NS",
"RPOWER.NS",
"SAGILITY.NS",
"SHYAMMETL.NS",
"SIGNATURE.NS",
"STARHEALTH.NS",
"SWANCORP.NS",
"TATACHEM.NS",
"TEJASNET.NS",
"RAMCOCEM.NS",
"TRIDENT.NS",
"TRITURBINE.NS",
"WELCORP.NS",
"WHIRLPOOL.NS",
"WOCKPHARMA.NS",
"ZENTEC.NS"
]

In [57]:
nifty_tickers=large_tickers + mid_tickers + small_tickers

In [ ]:
start_date = "2022-01-01"
end_date   = "2024-12-31"

all_data = []

for ticker in nifty_tickers:

    df = yf.download(ticker, start=start_date, end=end_date, multi_level_index=False, auto_adjust=True, progress=False)

    stock = yf.Ticker(ticker)
    info = stock.info
    
    if not df.empty:
        df["Stock"] = ticker.replace(".NS", "")
        df['Sector'] = stock.info.get('sector')
        df['Industry'] = stock.info.get('industry')
        df['Market Cap'] = stock.info.get('marketCap')
        df['Dividend Yield'] = stock.info.get('trailingAnnualDividendYield')
        df['Dividend Rate'] = stock.info.get('trailingAnnualDividendRate')
        df['PE Ratios'] = stock.info.get('trailingPE')
        df['ROE Values'] = stock.info.get('netIncomeToCommon') / (stock.info.get('bookValue') * stock.info.get('sharesOutstanding'))

        if ticker in large_tickers:
            df['Cap Category'] = 'Large Cap'
        elif ticker in mid_tickers:
            df['Cap Category'] = 'Mid Cap'
        elif ticker in small_tickers:
            df['Cap Category'] = 'Small Cap'
        else:
            df['Cap Category'] = None

        df.reset_index(inplace=True)   # Move Date from index to column
        all_data.append(df)

# Combine all stock data
stocks_df = pd.concat(all_data, ignore_index=True)

stocks_df.to_csv("nifty300_stocks.csv", index=False)
stocks_df

C:\Users\sulos\AppData\Local\Temp\ipykernel_13036\309759054.py:41: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  stocks_df = pd.concat(all_data, ignore_index=True)

,Date,Close,High,Low,Open,Volume,Stock,Sector,Industry,Market Cap,Dividend Yield,Dividend Rate,PE Ratios,ROE Values,Cap Category
0,2022-01-03,2165.453613,2227.458517,2145.963741,2210.619393,113948,ABB,Industrials,Specialty Industrial Machinery,1090798354432,0.008344,43.27,60.523220,0.249980,Large Cap
1,2022-01-04,2179.494141,2197.069423,2150.283666,2183.568783,353471,ABB,Industrials,Specialty Industrial Machinery,1090798354432,0.008344,43.27,60.523220,0.249980,Large Cap
2,2022-01-05,2185.826904,2209.097047,2160.102100,2189.116247,222632,ABB,Industrials,Specialty Industrial Machinery,1090798354432,0.008344,43.27,60.523220,0.249980,Large Cap
3,2022-01-06,2184.894287,2246.260827,2160.151346,2174.633850,423469,ABB,Industrials,Specialty Industrial Machinery,1090798354432,0.008344,43.27,60.523220,0.249980,Large Cap
4,2022-01-07,2186.710693,2222.892259,2176.302833,2196.381916,111305,ABB,Industrials,Specialty Industrial Machinery,1090798354432,0.008344,43.27,60.523220,0.249980,Large Cap
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200426,2024-12-23,2573.374268,2596.341908,2403.263845,2551.405221,1014490,ZENTEC,Industrials,Aerospace & Defense,125330620416,0.001409,2.00,49.351982,0.147664,Small Cap
200427,2024-12-24,2561.341064,2623.303809,2519.100532,2593.346019,632541,ZENTEC,Industrials,Aerospace & Defense,125330620416,0.001409,2.00,49.351982,0.147664,Small Cap
200428,2024-12-26,2461.032471,2558.395289,2436.616920,2558.395289,643354,ZENTEC,Industrials,Aerospace & Defense,125330620416,0.001409,2.00,49.351982,0.147664,Small Cap
200429,2024-12-27,2400.867188,2474.613377,2344.796289,2470.918388,428550,ZENTEC,Industrials,Aerospace & Defense,125330620416,0.001409,2.00,49.351982,0.147664,Small Cap
200430,2024-12-30,2426.081787,2454.541689,2326.771758,2352.834890,426254,ZENTEC,Industrials,Aerospace & Defense,125330620416,0.001409,2.00,49.351982,0.147664,Small Cap

In [7]:
nifty_df = yf.download('^NSEI', start=start_date, end=end_date, multi_level_index=False, auto_adjust=True)
nifty_df.reset_index(inplace=True)

nifty_df.to_csv('NIFTY50.csv', index=False)
 
nifty_df

[*********************100%***********************]  1 of 1 completed

          Date         Close          High           Low          Open  Volume
0   2022-01-03  17625.699219  17646.650391  17383.300781  17387.150391  200500
1   2022-01-04  17805.250000  17827.599609  17593.550781  17681.400391  247400
2   2022-01-05  17925.250000  17944.699219  17748.849609  17820.099609  251500
3   2022-01-06  17745.900391  17797.949219  17655.550781  17768.500000  236500
4   2022-01-07  17812.699219  17905.000000  17704.550781  17797.599609  239300
..         ...           ...           ...           ...           ...     ...
733 2024-12-23  23753.449219  23869.550781  23647.199219  23738.199219  189800
734 2024-12-24  23727.650391  23867.650391  23685.150391  23769.099609  177700
735 2024-12-26  23750.199219  23854.500000  23653.599609  23775.800781  177700
736 2024-12-27  23813.400391  23938.849609  23800.599609  23801.400391  176800
737 2024-12-30  23644.900391  23915.349609  23599.300781  23796.900391  364900

[738 rows x 6 columns]